import onepiece from "../assets/1.jpg";
import sololeveling from "../assets/2.jpg";
import SakamotoDays from "../assets/4.jpg";
import BlueBox from "../assets/8.jpg";
import Dandadan from "../assets/9.jpg";
import WindBreaker from "../assets/10.jpg";
import Naruto from "../assets/11.jpg";
import BlackClover from "../assets/13.jpg";
import ClassroomElite from "../assets/19.png";
import MyStar from "../assets/20.jpg";

export const movieData = [
  {
    id: "onepiece",
    label2: "1122",
    label3: "🎙1122",
    label1: "PG-13",
    label4: "HD",
    imageSrc: onepiece,
    title: "One Piece",
    redirectLink: "/onepiece",
          description: "Gold Roger was known as the Pirate King, the strongest and most infamous being to have sailed the Grand Line. The capture and execution of Roger by the World Government brought a change throughout the world. His last words before his death revealed the existence of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece—which promises an unlimited amount of riches and fame—and quite possibly the pinnacle of glory and the title of the Pirate King. Enter Monkey Luffy, a 17-year-old boy who defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate ransacking villages for fun, Luffy's reason for being a pirate is one of pure wonder: the thought of an exciting adventure that leads him to intriguing people and ultimately, the promised treasure. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach the most coveted of all fortunes—One Piece. [Written by MAL Rewrite]",
    rating: "8.62/10",
    premiered: "Fall 1999",
    genres: "Action, Adventure, Comedy, Drama, Fantasy, Shounen, Super Power",
    trailer: "https://www.youtube.com/embed/X3CR6L9uLd4?si=ysRZ81F401vNkm1H",
  },
  {
    id: "sololeveling",
    label2: "12",
    label3: "🎙12",
    label1: "PG-13",
    label4: "HD",
    imageSrc: sololeveling,
    title: "Solo Leveling",
    redirectLink: "/sololeveling",
    description: "Humanity was caught at a precipice a decade ago when the first gates—portals linked with other dimensions that harbor monsters immune to conventional weaponry—emerged around the world. Alongside the appearance of the gates, various humans were transformed into hunters and bestowed superhuman abilities. Responsible for entering the gates and clearing the dungeons within, many hunters chose to form guilds to secure their livelihoods. Sung Jin-Woo is an E-rank hunter dubbed as the weakest hunter of all mankind. While exploring a supposedly safe dungeon, he and his party encounter an unusual tunnel leading to a deeper area. Enticed by the prospect of treasure, the group presses forward, only to be confronted with horrors beyond their imagination. Miraculously, Jin-Woo survives the incident and soon finds that he now has access to an interface visible only to him. This mysterious system promises him the power he has long dreamed of—but everything comes at a price",
    rating: "8.39/10",
    premiered: "Winter 2024",
    genres: "Action, Adventure, Fantasy",
    trailer: "https://www.youtube.com/embed/I6JIwjWOhnQ?si=L98gHjiBqwFpGk7O",
  
  },
  {
    id: "Sakamoto Days",
    label2: "11",
    label3: "🎙11",
    label1: "PG-13",
    label4: "HD",
    imageSrc: SakamotoDays,
    title: "Sakamoto Days",
    redirectLink: "/SakamotoDays",
    description: "Tarou Sakamoto was considered the greatest hitman of all time. Feared by many, he stood at the top of the underground world until he met and fell in love with a woman. As a result, Sakamoto abandoned his life of crime and now works as a convenience store clerk. Leaving his shady past behind proves more difficult than Sakamoto initially imagined. Many of his former rivals and partners do not believe that he has truly left the business and show up in hopes of taking him out. Barred from killing, Sakamoto must find creative ways to subdue his enemies and prevent them from bringing harm to his family, his store, and the small town he resides in.",
    rating: "8.62/10",
    premiered: "Winter 2025",
    genres: " Action, Comedy, Shounen",
    trailer: "https://www.youtube.com/embed/TlP-RRo5b-8?si=8GH9a_wEnoNDzKJU",
  
  },
  {
    id: "Blue Box",
    label2: "25",
    label3: "🎙25",
    label1: "PG-13",
    label4: "HD",
    imageSrc: BlueBox,
    title: "Blue Box",
    redirectLink: "/BlueBox",
      description: "Taiki Inomata, a third-year student in junior high, attends Eimei Academy, an integrated school with a major sports program. Having joined the high school badminton team, Taiki tries to attend open practice as early as possible. But no matter how early he goes, he always arrives second in the gymnasium. The person one step ahead of him is Chinatsu Kano, a first-year student in senior high and Taiki's crush. Chinatsu is the rising star of the basketball team, and the gap between her and Taiki could not be greater. Although Taiki is a decent badminton player, his popularity is nowhere near Chinatsu's, making it even less likely for his feelings to be reciprocated. However, in a strange twist of fate, she ends up living in Taiki's house! Wanting to become a worthy match for Chinatsu, Taiki pursues the same dream as his crush: to partake in the Nationals. Taiki starts training harder than ever before, all for the sake of building a strong relationship with his new housemate. [Written by MAL Rewrite]",
    rating: "?/10",
    premiered: "Fall 2024",
    genres: "Romance, Sports",
    trailer: "https://www.youtube.com/embed/tcK9Eghsfq8?si=9kzS80QmwUKBGhAa",
  },
  {
    id: "Dandadan",
    label2: "12",
    label3: "🎙12",
    label1: "PG-13",
    label4: "HD",
    imageSrc: Dandadan,
    title: "Dandadan",
    redirectLink: "/Dandadan",
      description: "Reeling from her recent breakup, Momo Ayase, a popular high schooler, shows kindness to her socially awkward schoolmate, Ken Takakura, by standing up to his bullies. Ken misunderstands her intentions, believing he has made a new friend who shares his obsession with aliens and UFOs. However, Momo's own eccentric occult beliefs lie in the supernatural realm; she thinks aliens do not exist. A rivalry quickly brews as each becomes determined to prove the other wrong. Despite their initial clash over their opposing beliefs, Momo and Ken form an unexpected but intimate friendship, a bond forged in a series of supernatural battles and bizarre encounters with urban legends and paranormal entities. As both develop unique superhuman abilities, they learn to supplement each other's weaknesses, leading them to wonder if their newfound partnership may be about more than just survival.",
    rating: "8.73/10",
    premiered: "Fall 2024",
    genres: "Action, Comedy, Supernatural",
    trailer: "https://www.youtube.com/embed/NRxTXed7I7k?si=69AkrTRQWOF-CSfF",
  
  },
  {
    id: "Wind Breaker",
    label2: "13",
    label3: "🎙13",
    label1: "PG-13",
    label4: "HD",
    imageSrc: WindBreaker,
    title: "Wind Breaker",
    redirectLink: "/WindBreaker",
    description: "Gold Roger was known as the Pirate King, the strongest and most infamous being to have sailed the Grand Line. The capture and execution of Roger by the World Government brought a change throughout the world. His last words before his death revealed the existence of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece—which promises an unlimited amount of riches and fame—and quite possibly the pinnacle of glory and the title of the Pirate King. Enter Monkey Luffy, a 17-year-old boy who defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate ransacking villages for fun, Luffy's reason for being a pirate is one of pure wonder: the thought of an exciting adventure that leads him to intriguing people and ultimately, the promised treasure. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach the most coveted of all fortunes—One Piece. [Written by MAL Rewrite]",
    rating: "7.86/10",
    premiered: "Spring 2024",
    genres: "Action, Comedy, Drama, School",
    trailer: "https://www.youtube.com/embed/62r_G9bEPlU?si=DLGCILClCKiKqlgs",
  
  },
  {
    id: "Naruto",
    label2: "500",
    label3: "🎙500",
    label1: "PG-13",
    label4: "HD",
    imageSrc: Naruto,
    title: "Naruto",
    redirectLink: "/Naruto",
     description: "It has been two and a half years since Naruto Uzumaki left Konohagakure, the Hidden Leaf Village, for intense training following events which fueled his desire to be stronger. Now Akatsuki, the mysterious organization of elite rogue ninja, is closing in on their grand plan which may threaten the safety of the entire shinobi world. Although Naruto is older and sinister events loom on the horizon, he has changed little in personality—still rambunctious and childish—though he is now far more confident and possesses an even greater determination to protect his friends and home. Come whatever may, Naruto will carry on with the fight for what is important to him, even at the expense of his own body, in the continuation of the saga about the boy who wishes to become Hokage. [Written by MAL Rewrite]",
        rating: "8.15/10",
        premiered: "Winter 2007",
        genres: "Action, Adventure, Comedy, Martial Arts, Shounen, Super Power",
        trailer: "https://www.youtube.com/embed/-G9BqkgZXRA?si=2pfQEUmwwFblVPHm",
  },
  {
    id: "BlackClover",
    label2: "170",
    label3: "🎙170",
    label1: "PG-13",
    label4: "HD",
    imageSrc: BlackClover,
    title: "Black Clover",
    redirectLink: "/BlackClover",
    description: "Asta and Yuno were abandoned at the same church on the same day. Raised together as children, they came to know of the Wizard King—a title given to the strongest mage in the kingdom—and promised that they would compete against each other for the position of the next Wizard King. However, as they grew up, the stark difference between them became evident. While Yuno is able to wield magic with amazing power and control, Asta cannot use magic at all and desperately tries to awaken his powers by training physically. When they reach the age of 15, Yuno is bestowed a spectacular Grimoire with a four-leaf clover, while Asta receives nothing. However, soon after, Yuno is attacked by a person named Lebuty, whose main purpose is to obtain Yuno's Grimoire. Asta tries to fight Lebuty, but he is outmatched. Though without hope and on the brink of defeat, he finds the strength to continue when he hears Yuno's voice. Unleashing his inner emotions in a rage, Asta receives a five-leaf clover Grimoire, a Black Clover giving him enough power to defeat Lebuty. A few days later, the two friends head out into the world, both seeking the same goal—to become the Wizard King! [Written by MAL Rewrite]",
        rating: "7.29/10",
        premiered: "Fall 2017",
        genres: "Action, Fantasy, Shounen",
        trailer: "https://www.youtube.com/embed/PrgxJ1_sUcs",
  },
  {
    id: "Classroom of the Elite",
    label2: "12",
    label3: "🎙12",
    label1: "PG-13",
    label4: "HD",
    imageSrc: ClassroomElite,
    title: "Classroom of the Elite",
    redirectLink: "/ClassroomoftheElite",
    description: "On the surface, Koudo Ikusei Senior High School is a utopia. The students enjoy an unparalleled amount of freedom, and it is ranked highly in Japan. However, the reality is less than ideal. Four classes, A through D, are ranked in order of merit, and only the top classes receive favorable treatment. Kiyotaka Ayanokouji is a student of Class D, where the school dumps its worst. There he meets the unsociable Suzune Horikita, who believes she was placed in Class D by mistake and desires to climb all the way to Class A, and the seemingly amicable class idol Kikyou Kushida, whose aim is to make as many friends as possible. While class membership is permanent, class rankings are not; students in lower ranked classes can rise in rankings if they score better than those in the top ones. Additionally, in Class D, there are no bars on what methods can be used to get ahead. In this cutthroat school, can they prevail against the odds and reach the top?",
    rating: "7.86/10",
    premiered: "Summer 2017",
    genres: "Drama, School, Slice of Life, Psychological",
    trailer: "https://www.youtube.com/embed/6Gx4pQ14HLk?si=bohKfFlDcHHzrFMR",
  },
  {
    id: "My Star",
    label2: "11",
    label3: "🎙11",
    label1: "PG-13",
    label4: "HD",
    imageSrc: MyStar,
    title: "My Star",
    redirectLink: "/MyStar",
      description: "In the entertainment world, celebrities often show exaggerated versions of themselves to the public, concealing their true thoughts and struggles beneath elaborate lies. Fans buy into these fabrications, showering their idols with undying love and support, until something breaks the illusion. Sixteen-year-old rising star Ai Hoshino of pop idol group B Komachi has the world captivated; however, when she announces a hiatus due to health concerns, the news causes many to become worried. As a huge fan of Ai, gynecologist Gorou Amemiya cheers her on from his countryside medical practice, wishing he could meet her in person one day. His wish comes true when Ai shows up at his hospital—not sick, but pregnant with twins! While the doctor promises Ai to safely deliver her children, he wonders if this encounter with the idol will forever change the nature of his relationship with her",
    rating: "9.33/10",
    premiered: "Spring 2023",
    genres: "Drama, Music, Supernatural, Seinen",
    trailer: "https://www.youtube.com/embed/zntY4A4GPU0?si=ccDzr0025zxzIqjs",
  },
];
